package net.sfelabs.knox.core.android

import android.content.Context

/**
 * Mixin interface that provides access to the Android Application context.
 *
 * Classes that need Android context (such as use cases accessing Knox APIs or system services)
 * can implement this interface to gain access to [applicationContext] without constructor
 * parameters.
 *
 * ## Usage
 *
 * ```kotlin
 * class GetBrightnessValueUseCase :
 *     WithAndroidApplicationContext,
 *     SuspendingUseCase<Unit, Int>() {
 *
 *     override suspend fun execute(params: Unit): ApiResult<Int> {
 *         val brightness = Settings.System.getInt(
 *             applicationContext.contentResolver,
 *             Settings.System.SCREEN_BRIGHTNESS
 *         )
 *         return ApiResult.Success(brightness)
 *     }
 * }
 * ```
 *
 * ## Why This Pattern?
 *
 * This interface exists because KSP-generated code requires classes with empty constructors.
 * The KSP processor generates policy components that instantiate policies and use cases
 * without parameters:
 *
 * ```kotlin
 * // Generated by KSP - cannot pass dependencies
 * private val policyImpl = MyPolicy()
 * ```
 *
 * By implementing this interface, use cases can access Android context without requiring
 * it as a constructor parameter, making them compatible with KSP code generation.
 *
 * ## Prerequisites
 *
 * [AndroidApplicationContextProvider.init] must be called before accessing [applicationContext],
 * typically in your Application's `onCreate()` method.
 *
 * @see AndroidApplicationContextProvider for details on the architecture and rationale
 */
interface WithAndroidApplicationContext {
    /**
     * The Application context, retrieved from [AndroidApplicationContextProvider].
     *
     * @throws IllegalStateException if [AndroidApplicationContextProvider.init] has not been called
     */
    val applicationContext: Context
        get() = AndroidApplicationContextProvider.get()
}