package net.sfelabs.knox.core.feature.api

import net.sfelabs.knox.core.feature.domain.usecase.handler.PolicyHandler

/**
 * Component that wraps a policy and provides all necessary metadata and handlers.
 *
 * PolicyComponents are generated by the KSP processor for each class annotated
 * with `@PolicyDefinition`. They serve as the primary interface for interacting
 * with policies at runtime, providing:
 * - Metadata (name, title, description, category, capabilities)
 * - State management (handler, defaultValue)
 * - UI conversion (uiConverter)
 * - Type-safe key for lookups
 *
 * @param T The PolicyState type this component handles
 */
interface PolicyComponent<T : PolicyState> {
    val policyName: String
    val title: String
    val description: String
    val category: PolicyCategory
    val handler: PolicyHandler<T>
    val defaultValue: T
    val key: PolicyKey<T>

    /**
     * Converter for translating between domain state and UI state.
     *
     * This enables polymorphic UI conversion, eliminating the need for
     * manual dispatch (when statements) in ViewModels based on policy type.
     */
    val uiConverter: PolicyUiConverter<T>

    /**
     * Intrinsic capabilities of this policy.
     *
     * Capabilities describe what the policy modifies (radio, display, etc.),
     * device requirements (SIM, HDM), and impact characteristics. These are
     * factual properties used for filtering and grouping.
     *
     * @see PolicyCapability
     */
    val capabilities: Set<PolicyCapability>

    /**
     * Check if this policy has a specific capability.
     */
    fun hasCapability(capability: PolicyCapability): Boolean = capability in capabilities

    /**
     * Check if this policy has all of the specified capabilities.
     */
    fun hasAllCapabilities(caps: Set<PolicyCapability>): Boolean = capabilities.containsAll(caps)

    /**
     * Check if this policy has any of the specified capabilities.
     */
    fun hasAnyCapability(caps: Set<PolicyCapability>): Boolean = capabilities.any { it in caps }
}